# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "common",
    srcs = ["fileio.cc", "fillz.cc", "getmem.cc", "movem.cc", "getfp.cc", "frameseq.cc"],
    hdrs = ["common.hpp"],
    deps = [],
    visibility = ["//bin:__subpackages__"],
)

